- name: installing jenkins in ubuntu 16.04
  hosts: jenkins
  gather_facts: true
  become: yes
  
  tasks:
#  - name: install python 2
#    become: yes
#    raw: sudo test -e /usr/bin/python || (sudo apt -y update && sudo apt install -y python2-minimal)

  - name: install curl and git
#    become: yes
    apt:
      pkg:
      - default-jre
      - vim
      - git
      - curl
      state: present

  - name: adding jenkins gpg key
    become: yes
    raw: wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -

  - name: jeknins repository to system
    become: yes
    raw: sudo sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'

  - name: apt update to pull in jenkins package
    become: yes
    raw: sudo apt update

  - name: installing jenkins
    become: yes
    apt:
      name: jenkins
      state: present
      update_cache: yes

  - name: adding jenkins to startup
    become: yes
    service:
      name: jenkins
      state: started
      enabled: yes

  - name: printing jenkins default administration password
    command: cat /var/lib/jenkins/secrets/initialAdminPassword
    register: jenkins_default_admin_password
  
  - debug:
      msg: "{{ jenkins_default_admin_password.stdout }}"
